### ISSUE TITLE
Add query / command request processing verticle to storage manager sdk to better leverage vertx event loop threading

### ISSUE THREAD

**Issue by mer2github** [Vantiq/vantiq-service-connectors#21]

**Comment by rblumer4** [comment]
what milestone are you targeting?

**Comment by mer2github** [comment]
@rblumer4 Planning to have this be ready before Vantiq 1.38.0 releases. 

Service connectors release independently from the server (though they might have minimum server release requirements), so we don't have formal milestones here.
